### ISSUE TITLE
Bootmem.c

### ISSUE THREAD

**Issue by liuzuanmin** [minosproject/minos-hypervisor#8]
计算bootmem的时候应该是从CONFIG_MINOS_START_ADDRESS开始计算吧，而不应该从__code_start计算，不知道我的理解是否对。望指正

**Comment by lemin9538** [comment]
看了下代码，从CONFIG_MINOS_START_ADDRESS开始计算是对的。你理解的很正确。方便的话，是否可以提个patch修正下？

**Comment by liuzuanmin** [comment]
好的，我周末提交一下

**Comment by lemin9538** [comment]
周末我已经提了一个，后续如果发现问题可以直接提交修复 后提一个pull request， 感谢。
